"""Type stubs for the _ftxui C extension module."""

from __future__ import annotations
from typing import Callable, Optional, Tuple

# ── Opaque DOM/Component types ─────────────────────────────────────────────

class Element:
    """Opaque FTXUI element (std::shared_ptr<Node>)."""
    ...

class Component:
    """Opaque FTXUI component (std::shared_ptr<ComponentBase>)."""
    ...

# ── Color ─────────────────────────────────────────────────────────────────

class Color:
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Color: ...

COLOR_DEFAULT: Color
COLOR_BLACK: Color
COLOR_WHITE: Color
COLOR_RED: Color
COLOR_GREEN: Color
COLOR_BLUE: Color
COLOR_CYAN: Color
COLOR_YELLOW: Color
COLOR_MAGENTA: Color
COLOR_GRAY_LIGHT: Color
COLOR_GRAY_DARK: Color

# ── DOM functions ─────────────────────────────────────────────────────────

def hbox(elements: list[Element]) -> Element: ...
def vbox(elements: list[Element]) -> Element: ...
def dbox(elements: list[Element]) -> Element: ...
def border(e: Element) -> Element: ...
def border_rounded(e: Element) -> Element: ...
def border_light(e: Element) -> Element: ...
def border_heavy(e: Element) -> Element: ...
def window(title: Element, content: Element) -> Element: ...
def separator() -> Element: ...
def separator_light() -> Element: ...
def separator_heavy() -> Element: ...
def empty_element() -> Element: ...
def flex(e: Element) -> Element: ...
def flex_grow(e: Element) -> Element: ...
def xflex(e: Element) -> Element: ...
def yflex(e: Element) -> Element: ...
def notflex(e: Element) -> Element: ...
def spinner(charset_index: int, frame_index: int = 0) -> Element: ...
def gauge(progress: float) -> Element: ...
def gauge_left(progress: float) -> Element: ...
def gauge_right(progress: float) -> Element: ...
def paragraph(text: str) -> Element: ...
def vtext(text: str) -> Element: ...
def _text_raw(text: str) -> Element: ...
def _bold(e: Element) -> Element: ...
def _dim(e: Element) -> Element: ...
def _italic(e: Element) -> Element: ...
def _inverted(e: Element) -> Element: ...
def _color_element(color: Color, e: Element) -> Element: ...
def _bgcolor_element(color: Color, e: Element) -> Element: ...
def markdown(md: str) -> Element: ...
def markdown_with_width(md: str, width: int) -> Element: ...
def markdown_component(md: str) -> Component: ...

# ── Component factories ────────────────────────────────────────────────────

def make_renderer(fn: Callable[[], Element]) -> Component: ...
def make_button(label: str, on_click: Callable[[], None]) -> Component: ...
def make_button_animated(label: str, on_click: Callable[[], None]) -> Component: ...
def make_input(
    placeholder: str = "",
    value: Optional[object] = None,
) -> Tuple[Component, Callable[[], str]]: ...
def make_checkbox(
    label: str,
    checked: bool = False,
    on_change: Optional[Callable[[bool], None]] = None,
) -> Tuple[Component, Callable[[], bool], Callable[[bool], None]]: ...
def container_vertical(components: list[Component]) -> Component: ...
def container_horizontal(components: list[Component]) -> Component: ...

# ── App control ───────────────────────────────────────────────────────────

def run_fullscreen(component: Component) -> None: ...
def run(component: Component) -> None: ...
def run_fit_component(component: Component) -> None: ...
def app_exit() -> None: ...
def app_post_event() -> None: ...

# ── Theme ─────────────────────────────────────────────────────────────────

class Theme:
    @staticmethod
    def default_theme() -> Theme: ...
    @staticmethod
    def dark() -> Theme: ...
    @staticmethod
    def light() -> Theme: ...
    @staticmethod
    def nord() -> Theme: ...
    @staticmethod
    def dracula() -> Theme: ...
    @staticmethod
    def monokai() -> Theme: ...

def set_theme(theme: Theme) -> None: ...
def get_theme() -> Theme: ...

# ── Reactive ──────────────────────────────────────────────────────────────

class ReactiveInt:
    def __init__(self, initial: int = 0) -> None: ...
    def get(self) -> int: ...
    def set(self, value: int) -> None: ...
    def on_change(self, fn: Callable[[int], None]) -> int: ...
    def remove_listener(self, id: int) -> None: ...
    def notify(self) -> None: ...

class ReactiveFloat:
    def __init__(self, initial: float = 0.0) -> None: ...
    def get(self) -> float: ...
    def set(self, value: float) -> None: ...
    def on_change(self, fn: Callable[[float], None]) -> int: ...
    def remove_listener(self, id: int) -> None: ...
    def notify(self) -> None: ...

class ReactiveStr:
    def __init__(self, initial: str = "") -> None: ...
    def get(self) -> str: ...
    def set(self, value: str) -> None: ...
    def on_change(self, fn: Callable[[str], None]) -> int: ...
    def remove_listener(self, id: int) -> None: ...
    def notify(self) -> None: ...

# ── LogPanel ──────────────────────────────────────────────────────────────

class LogLevel:
    TRACE: LogLevel
    DEBUG: LogLevel
    INFO: LogLevel
    WARN: LogLevel
    ERROR: LogLevel

class LogPanel:
    @staticmethod
    def create(max_lines: int = 1000) -> LogPanel: ...
    def log(self, message: str, level: LogLevel = LogLevel.INFO) -> None: ...
    def trace(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def clear(self) -> None: ...
    def set_max_lines(self, n: int) -> None: ...
    def set_min_level(self, level: LogLevel) -> None: ...
    def build(self, title: str = "") -> Component: ...
