// Copyright 2024 Arthur Sonzogni. All rights reserved.
// Use of this source code is governed by the MIT license that can be found in
// the LICENSE file.

/// @file codegen.cpp
/// @brief AI Code Generator — CodeGenerator, TemplateLibrary,
/// SyntaxHighlighter,
///        CodeGenStudio, CodePreview.

#include "ftxui/ui/codegen.hpp"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <ctime>
#include <fstream>
#include <functional>
#include <map>
#include <memory>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

// POSIX socket headers for raw Ollama HTTP calls
#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#else
#include <arpa/inet.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

#include "ftxui/component/component.hpp"
#include "ftxui/component/component_base.hpp"
#include "ftxui/component/event.hpp"
#include "ftxui/component/screen_interactive.hpp"
#include "ftxui/dom/elements.hpp"
#include "ftxui/ui/llm_bridge.hpp"
#include "ftxui/ui/tree.hpp"

using namespace ftxui;

namespace ftxui::ui {

// ═════════════════════════════════════════════════════════════════════════════
// Template strings
// ═════════════════════════════════════════════════════════════════════════════

static const std::string DASHBOARD_TEMPLATE =
    R"(// {APP_NAME} — Generated by BadWolf Code Generator
// {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  auto log = LogPanel::Create(200);
  log->Add("[info]  {APP_NAME} started");

  auto tab_index = std::make_shared<int>(0);

  auto overview = Renderer([&] {
    return vbox({
      text(" {APP_NAME} Dashboard") | bold | color(Color::Cyan) | hcenter,
      separator(),
      hbox({
        vbox({
          text("Status") | bold,
          text("● Running") | color(Color::Green),
          text("● 3 services OK") | color(Color::Green),
        }) | border | flex,
        vbox({
          text("Uptime") | bold,
          text("2d 14h 33m"),
        }) | border | flex,
        vbox({
          text("Alerts") | bold,
          text("0 critical") | color(Color::Green),
          text("2 warnings") | color(Color::Yellow),
        }) | border | flex,
      }) | flex,
    });
  });

  auto app = Tab(
    {{"Overview", overview}, {"Log", log}},
    tab_index.get()
  );

  ScreenInteractive::Fullscreen().Loop(app);
  return 0;
}
)";

static const std::string MONITOR_TEMPLATE = R"(// {APP_NAME} — System Monitor
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
#include <vector>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  // Simulated metrics
  auto cpu = std::make_shared<float>(0.42f);
  auto mem = std::make_shared<float>(0.67f);

  std::vector<std::vector<std::string>> procs = {
    {"PID",  "Name",       "CPU%", "MEM%"},
    {"1234", "nginx",      "2.1",  "1.4"},
    {"1235", "postgres",   "5.3",  "12.2"},
    {"1236", "{APP_NAME}", "0.1",  "0.8"},
  };

  auto table = DataTable::Create(procs);
  auto log   = LogPanel::Create(100);
  log->Add("[info]  monitor started");

  auto monitor = Renderer([&] {
    return vbox({
      text(" {APP_NAME} Monitor") | bold | color(Color::Green) | hcenter,
      separator(),
      hbox({
        vbox({
          text("CPU") | bold,
          gauge(*cpu) | color(Color::Cyan),
          text(std::to_string(int(*cpu * 100)) + "%") | color(Color::Cyan),
        }) | border | flex,
        vbox({
          text("Memory") | bold,
          gauge(*mem) | color(Color::Yellow),
          text(std::to_string(int(*mem * 100)) + "%") | color(Color::Yellow),
        }) | border | flex,
      }),
      text("Processes") | bold,
      table->Render() | flex,
    });
  });

  auto root = Tab(
    {{"Monitor", monitor}, {"Log", log}},
    nullptr
  );

  ScreenInteractive::Fullscreen().Loop(root);
  return 0;
}
)";

static const std::string CRUD_TEMPLATE = R"(// {APP_NAME} — CRUD Application
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
#include <vector>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  std::vector<std::vector<std::string>> rows = {
    {"ID", "Name",  "Email",             "Status"},
    {"1",  "Alice", "alice@example.com", "Active"},
    {"2",  "Bob",   "bob@example.com",   "Active"},
    {"3",  "Carol", "carol@example.com", "Inactive"},
  };

  auto table = DataTable::Create(rows);

  // Create form
  auto name_val  = std::make_shared<std::string>();
  auto email_val = std::make_shared<std::string>();

  FormSpec spec;
  spec.title = "Add {APP_NAME} Record";
  spec.fields = {
    {"Name",  "text",  name_val.get()},
    {"Email", "email", email_val.get()},
  };

  auto form  = Form::Create(spec);
  auto log   = LogPanel::Create(50);

  int tab = 0;
  auto root = Tab(
    {{"List", table}, {"New", form}, {"Log", log}},
    &tab
  );

  ScreenInteractive::Fullscreen().Loop(root);
  return 0;
}
)";

static const std::string CHAT_TEMPLATE = R"(// {APP_NAME} — Chat UI
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
#include <vector>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  struct Message { std::string author, text, time; };
  auto messages = std::make_shared<std::vector<Message>>(std::vector<Message>{
    {"Alice", "Hey, how's it going?",  "09:00"},
    {"Bob",   "Pretty good! Working on some {APP_NAME} stuff.", "09:01"},
    {"Alice", "Nice, sounds fun.",     "09:02"},
  });

  std::string input_text;
  auto input = Input(&input_text, "Type a message…");

  auto chat_view = Renderer(input, [&] {
    Elements lines;
    for (auto& m : *messages) {
      lines.push_back(hbox({
        text(m.time)   | dim | size(WIDTH, EQUAL, 6),
        text(" "),
        text(m.author) | bold | color(Color::Cyan)
                       | size(WIDTH, EQUAL, 10),
        text(": "),
        text(m.text)   | flex,
      }));
    }
    lines.push_back(separator());
    lines.push_back(hbox({
      text("> ") | color(Color::Green),
      input->Render() | flex,
    }));
    return vbox({
      text(" {APP_NAME}") | bold | hcenter,
      separator(),
      vbox(lines) | flex,
    }) | border;
  });

  chat_view |= CatchEvent([&](Event ev) {
    if (ev == Event::Return && !input_text.empty()) {
      messages->push_back({"You", input_text, "now"});
      input_text.clear();
      return true;
    }
    return false;
  });

  ScreenInteractive::Fullscreen().Loop(chat_view);
  return 0;
}
)";

static const std::string EXPLORER_TEMPLATE =
    R"(// {APP_NAME} — File/Data Explorer
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
#include <vector>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  // Tree data
  TreeNode root_node;
  root_node.label = "{APP_NAME}";
  root_node.children = {
    {.label = "src",      .children = {{.label = "main.cpp"}, {.label = "util.cpp"}}},
    {.label = "include",  .children = {{.label = "app.hpp"}}},
    {.label = "README.md"},
    {.label = "CMakeLists.txt"},
  };

  auto selected = std::make_shared<std::string>("-- select an item --");
  auto tree = Tree::Create(root_node, [&](const TreeNode& n) {
    *selected = n.label;
  });

  auto detail = Renderer([&] {
    return vbox({
      text("Detail") | bold,
      separator(),
      text(*selected),
    }) | border | flex;
  });

  auto split = ResizableSplitLeft(
    tree | border | size(WIDTH, EQUAL, 30),
    detail,
    nullptr
  );

  ScreenInteractive::Fullscreen().Loop(split);
  return 0;
}
)";

static const std::string WIZARD_TEMPLATE = R"(// {APP_NAME} — Multi-Step Wizard
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  std::string name, email, plan;

  WizardSpec spec;
  spec.title = "{APP_NAME} Setup";
  spec.steps = {
    {.title = "Welcome",
     .content = Renderer([] {
       return vbox({
         text("Welcome to {APP_NAME}!") | bold | hcenter,
         text("This wizard will guide you through setup.") | hcenter,
       });
     })},
    {.title = "Profile",
     .content = Form::Create(FormSpec{
       .title = "Your Profile",
       .fields = {{"Name", "text", &name}, {"Email", "email", &email}},
     })},
    {.title = "Plan",
     .content = Form::Create(FormSpec{
       .title = "Choose Plan",
       .fields = {{"Plan", "select:Free,Pro,Enterprise", &plan}},
     })},
    {.title = "Done",
     .content = Renderer([&] {
       return vbox({
         text("All set!") | bold | color(Color::Green) | hcenter,
         text("Name:  " + name),
         text("Email: " + email),
         text("Plan:  " + plan),
       });
     })},
  };

  auto wiz = Wizard::Create(spec);
  ScreenInteractive::Fullscreen().Loop(wiz);
  return 0;
}
)";

static const std::string GAME_TEMPLATE = R"(// {APP_NAME} — Game Loop Demo
// Generated by BadWolf Code Generator — {TIMESTAMP}
#include <ftxui/ui.hpp>
#include <string>
using namespace ftxui;
using namespace ftxui::ui;

int main() {
  SetTheme(Theme::Dark());

  // Simple physics world
  auto world = PhysicsWorld::Create();

  float px = 20.0f, py = 10.0f;
  float vx = 0.0f,  vy = 0.0f;

  auto game = Renderer([&] {
    // Draw the player
    auto c = Canvas(80, 40);
    c.DrawText(int(px), int(py), "@", [](Pixel& p) {
      p.foreground_color = Color::Yellow;
      p.bold = true;
    });
    return vbox({
      text(" {APP_NAME}") | bold | hcenter,
      separator(),
      canvas(std::move(c)) | border | flex,
      text("WASD to move | Q to quit") | dim | hcenter,
    });
  });

  game |= CatchEvent([&](Event ev) {
    if (ev == Event::Character('w')) { vy -= 1.0f; return true; }
    if (ev == Event::Character('s')) { vy += 1.0f; return true; }
    if (ev == Event::Character('a')) { vx -= 1.0f; return true; }
    if (ev == Event::Character('d')) { vx += 1.0f; return true; }
    return false;
  });

  ScreenInteractive::Fullscreen().Loop(game);
  return 0;
}
)";

static const std::string MAP_TEMPLATE =
    "// {APP_NAME} \xe2\x80\x94 GeoMap Overlay\n"
    "// Generated by BadWolf Code Generator \xe2\x80\x94 {TIMESTAMP}\n"
    "#include <ftxui/ui.hpp>\n"
    "#include <string>\n"
    "#include <vector>\n"
    "using namespace ftxui;\n"
    "using namespace ftxui::ui;\n"
    "\n"
    "int main() {\n"
    "  SetTheme(Theme::Dark());\n"
    "\n"
    "  GeoMapOptions opts;\n"
    "  opts.title = \"{APP_NAME} World Overview\";\n"
    "  opts.color_scheme = GeoColorScheme::Green;\n"
    "  opts.show_legend  = true;\n"
    "\n"
    "  opts.data = {\n"
    "    {\"US\", 95.0f},\n"
    "    {\"DE\", 72.0f},\n"
    "    {\"JP\", 88.0f},\n"
    "    {\"BR\", 61.0f},\n"
    "    {\"IN\", 54.0f},\n"
    "  };\n"
    "\n"
    "  auto selected_country = std::make_shared<std::string>(\"none\");\n"
    "\n"
    "  auto geomap = GeoMap::Create(opts, [&](const std::string& c) {\n"
    "    *selected_country = c;\n"
    "  });\n"
    "\n"
    "  auto info = Renderer([&] {\n"
    "    return vbox({\n"
    "      text(\"Selected: \" + *selected_country) | bold,\n"
    "    }) | border;\n"
    "  });\n"
    "\n"
    "  auto root = vbox({geomap->Render() | flex, info->Render()});\n"
    "  ScreenInteractive::Fullscreen().Loop(Renderer([&] { return root; }));\n"
    "  return 0;\n"
    "}\n";

static const std::string DEFAULT_CMAKE = R"(
# Add this to your CMakeLists.txt
cmake_minimum_required(VERSION 3.12)
project({APP_NAME} CXX)

find_package(ftxui REQUIRED)

add_executable({APP_NAME} {APP_NAME}.cpp)
target_link_libraries({APP_NAME} PRIVATE
    ftxui::ui
    ftxui::component
    ftxui::dom
    ftxui::screen
)
target_compile_features({APP_NAME} PRIVATE cxx_std_17)
)";

// ═════════════════════════════════════════════════════════════════════════════
// TemplateLibrary
// ═════════════════════════════════════════════════════════════════════════════

const std::vector<CodeTemplate>& TemplateLibrary::BuiltinTemplates() {
  static std::vector<CodeTemplate> templates = {
      {
          "dashboard",
          "Multi-tab dashboard with status, charts, and log panel",
          {"dashboard", "overview", "status", "multi", "tab", "tabs", "panel",
           "summary", "admin", "control"},
          DASHBOARD_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "monitor",
          "Real-time sysmon-style display with CPU/memory bars and process "
          "table",
          {"monitor", "monitoring", "sysmon", "system", "cpu", "memory", "ram",
           "process", "processes", "metrics", "performance", "stats",
           "kubernetes", "pod", "container", "k8s", "server", "resource"},
          MONITOR_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "crud",
          "Create / Read / Update / Delete data application with form and "
          "table",
          {"crud", "create", "edit", "delete", "form", "record", "records",
           "data", "database", "manage", "management", "list", "entry",
           "entries"},
          CRUD_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "chat",
          "Chat / messaging UI with message list, input, and timestamps",
          {"chat", "message", "messages", "messaging", "conversation", "talk",
           "discuss", "irc", "slack", "discord", "send", "inbox"},
          CHAT_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "explorer",
          "File / data explorer with tree on left and detail view on right",
          {"explorer", "explore", "file", "files", "tree", "folder", "folders",
           "directory", "browse", "browser", "navigate", "navigation",
           "inspect", "viewer", "detail"},
          EXPLORER_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "wizard",
          "Multi-step wizard form using the Wizard component",
          {"wizard", "setup", "install", "installation", "onboarding", "step",
           "steps", "multi-step", "guide", "configure", "configuration",
           "deploy", "deployment"},
          WIZARD_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "game",
          "Basic game loop with canvas rendering and WASD controls",
          {"game", "games", "play", "player", "move", "physics", "canvas",
           "sprite", "loop", "engine", "adventure", "roguelike", "arcade"},
          GAME_TEMPLATE,
          DEFAULT_CMAKE,
      },
      {
          "map",
          "GeoMap with data overlay, legend, and click-to-select country info",
          {"map", "geo", "geographic", "world", "country", "countries",
           "region", "regions", "location", "locations", "globe", "earth",
           "geospatial", "cartography"},
          MAP_TEMPLATE,
          DEFAULT_CMAKE,
      },
  };
  return templates;
}

const CodeTemplate* TemplateLibrary::FindBest(const std::string& description) {
  // Lower-case copy for case-insensitive matching
  std::string lower = description;
  std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);

  const CodeTemplate* best = nullptr;
  int best_score = 0;

  for (const auto& tmpl : BuiltinTemplates()) {
    int score = 0;
    for (const auto& kw : tmpl.keywords) {
      if (lower.find(kw) != std::string::npos) {
        ++score;
      }
    }
    if (score > best_score) {
      best_score = score;
      best = &tmpl;
    }
  }

  return (best_score >= 1) ? best : nullptr;
}

std::string TemplateLibrary::Fill(
    const CodeTemplate& tmpl,
    const std::map<std::string, std::string>& vars) {
  std::string result = tmpl.code;

  // Apply caller-provided substitutions
  for (const auto& [key, value] : vars) {
    std::string placeholder = "{" + key + "}";
    std::string::size_type pos = 0;
    while ((pos = result.find(placeholder, pos)) != std::string::npos) {
      result.replace(pos, placeholder.size(), value);
      pos += value.size();
    }
  }

  return result;
}

// ═════════════════════════════════════════════════════════════════════════════
// CodeGenResult helpers
// ═════════════════════════════════════════════════════════════════════════════

bool CodeGenResult::WriteToFile(const std::string& path) const {
  std::ofstream f(path);
  if (!f.is_open()) {
    return false;
  }
  f << code;
  return f.good();
}

bool CodeGenResult::LooksValid() const {
  if (code.empty()) {
    return false;
  }
  // Must reference ftxui in some way
  bool has_ftxui = code.find("ftxui") != std::string::npos;
  // Must have a main function
  bool has_main = code.find("main(") != std::string::npos ||
                  code.find("main ()") != std::string::npos;
  return has_ftxui && has_main;
}

// ═════════════════════════════════════════════════════════════════════════════
// CodeGenerator
// ═════════════════════════════════════════════════════════════════════════════

CodeGenerator::CodeGenerator(std::string model) : model_(std::move(model)) {}

std::string CodeGenerator::ModelName() const {
  return model_;
}

bool CodeGenerator::LLMAvailable() const {
  return LLMAdapter::OllamaAvailable();
}

std::string CodeGenerator::BuildSystemPrompt() {
  return "You are an expert FTXUI BadWolf C++ developer. "
         "Generate complete, compilable terminal UI applications.\n\n"
         "Rules:\n"
         "1. Always include: #include <ftxui/ui.hpp>\n"
         "2. Use namespace ftxui::ui for all BadWolf components\n"
         "3. Use ftxui:: for core FTXUI types\n"
         "4. Return ONLY C++ code in ```cpp blocks, no explanation\n"
         "5. Code must compile with: "
         "g++ -std=c++17 -lftxui_ui -lftxui_component -lftxui_dom "
         "-lftxui_screen\n\n"
         "Available components: Theme, Form, DataTable, Chart, LineChart, "
         "BarChart,\n"
         "GeoMap, Animation, PhysicsWorld, GameLoop, TypewriterText, Console,\n"
         "JsonTreeView, ReactiveQuery, DataFrame, LogPanel, Tree, Router,\n"
         "TimeTravelDebugger, VoiceInputBar, WebBridge, PluginRegistry, and "
         "more.\n"
         "Always call SetTheme(Theme::Dark()) at the start of main().\n"
         "Always end with "
         "ScreenInteractive::Fullscreen().Loop(root_component);\n";
}

std::string CodeGenerator::BuildUserPrompt(const CodeGenRequest& req) {
  std::ostringstream oss;
  oss << "Generate a complete FTXUI BadWolf C++ terminal application.\n\n";
  oss << "Description: " << req.description << "\n";
  oss << "Style: " << req.style << "\n";

  if (!req.features.empty()) {
    oss << "Features to include: ";
    for (std::size_t i = 0; i < req.features.size(); ++i) {
      if (i > 0) {
        oss << ", ";
      }
      oss << req.features[i];
    }
    oss << "\n";
  }

  if (req.include_cmake) {
    oss << "Also include a CMakeLists.txt snippet in a ```cmake block.\n";
  }
  if (req.include_comments) {
    oss << "Add helpful comments explaining key sections.\n";
  }

  oss << "\nReturn only the code, no prose.\n";
  return oss.str();
}

// Simple synchronous HTTP call to Ollama /api/generate
std::string CodeGenerator::QueryOllama(const std::string& system_prompt,
                                       const std::string& user_prompt) {
#ifdef _WIN32
  WSADATA wsa;
  WSAStartup(MAKEWORD(2, 2), &wsa);
#endif

  // Connect to localhost:11434
  struct addrinfo hints{}, *res = nullptr;
  hints.ai_family = AF_INET;
  hints.ai_socktype = SOCK_STREAM;
  if (getaddrinfo("127.0.0.1", "11434", &hints, &res) != 0 || res == nullptr) {
    return {};
  }

  int sock = static_cast<int>(socket(res->ai_family, res->ai_socktype, 0));
  if (sock < 0) {
    freeaddrinfo(res);
    return {};
  }

  if (connect(sock, res->ai_addr, res->ai_addrlen) != 0) {
    freeaddrinfo(res);
#ifdef _WIN32
    closesocket(sock);
#else
    close(sock);
#endif
    return {};
  }
  freeaddrinfo(res);

  // Escape strings for JSON
  auto json_escape = [](const std::string& s) -> std::string {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
      if (c == '"') {
        out += "\\\"";
      } else if (c == '\\') {
        out += "\\\\";
      } else if (c == '\n') {
        out += "\\n";
      } else if (c == '\r') {
        out += "\\r";
      } else if (c == '\t') {
        out += "\\t";
      } else {
        out += c;
      }
    }
    return out;
  };

  // Build JSON body (non-streaming so we get one response)
  std::string body = "{\"model\":\"" + json_escape(model_) +
                     "\","
                     "\"prompt\":\"" +
                     json_escape(system_prompt + "\n\n" + user_prompt) +
                     "\","
                     "\"stream\":false}";

  std::string request =
      "POST /api/generate HTTP/1.0\r\n"
      "Host: 127.0.0.1:11434\r\n"
      "Content-Type: application/json\r\n"
      "Content-Length: " +
      std::to_string(body.size()) +
      "\r\n"
      "\r\n" +
      body;

  // Send
  std::size_t sent = 0;
  while (sent < request.size()) {
    int n = static_cast<int>(send(sock, request.data() + sent,
                                  static_cast<int>(request.size() - sent), 0));
    if (n <= 0) {
      break;
    }
    sent += static_cast<std::size_t>(n);
  }

  // Receive full response (up to 512 KB)
  std::string response;
  response.reserve(65536);
  char buf[4096];
  while (true) {
    int n = static_cast<int>(recv(sock, buf, sizeof(buf), 0));
    if (n <= 0) {
      break;
    }
    response.append(buf, static_cast<std::size_t>(n));
    if (response.size() > 512 * 1024) {
      break;
    }
  }

#ifdef _WIN32
  closesocket(sock);
  WSACleanup();
#else
  close(sock);
#endif

  // Extract the "response" field from the JSON
  auto find_str_field = [&](const std::string& key) -> std::string {
    std::string pattern = "\"" + key + "\":\"";
    auto pos = response.find(pattern);
    if (pos == std::string::npos) {
      return {};
    }
    pos += pattern.size();
    std::string out;
    while (pos < response.size()) {
      char c = response[pos++];
      if (c == '\\' && pos < response.size()) {
        char nc = response[pos++];
        if (nc == 'n') {
          out += '\n';
        } else if (nc == 't') {
          out += '\t';
        } else if (nc == '"') {
          out += '"';
        } else if (nc == '\\') {
          out += '\\';
        } else {
          out += '\\';
          out += nc;
        }
      } else if (c == '"') {
        break;
      } else {
        out += c;
      }
    }
    return out;
  };

  return find_str_field("response");
}

void CodeGenerator::ExtractCode(const std::string& llm_response,
                                CodeGenResult& result) {
  // Extract ```cpp ... ``` block
  auto extract_block = [&](const std::string& fence) -> std::string {
    auto start = llm_response.find(fence);
    if (start == std::string::npos) {
      return {};
    }
    start += fence.size();
    // Skip to end of line
    auto nl = llm_response.find('\n', start);
    if (nl == std::string::npos) {
      return {};
    }
    start = nl + 1;
    auto end = llm_response.find("```", start);
    if (end == std::string::npos) {
      return llm_response.substr(start);
    }
    return llm_response.substr(start, end - start);
  };

  std::string cpp_code = extract_block("```cpp");
  if (cpp_code.empty()) {
    cpp_code = extract_block("```c++");
  }
  if (cpp_code.empty()) {
    cpp_code = extract_block("```");
  }

  if (!cpp_code.empty()) {
    result.code = cpp_code;
  } else {
    // Fallback: use whole response as code if it looks like C++
    if (llm_response.find("#include") != std::string::npos) {
      result.code = llm_response;
    }
  }

  // Extract CMake snippet
  std::string cmake = extract_block("```cmake");
  if (cmake.empty()) {
    cmake = extract_block("```CMake");
  }
  if (!cmake.empty()) {
    result.cmake_snippet = cmake;
  }
}

// Build default variable substitutions for a request
static std::map<std::string, std::string> DefaultVars(
    const CodeGenRequest& req) {
  // Extract "app name": capitalize first word of description
  std::string app_name;
  {
    std::istringstream ss(req.description);
    std::string word;
    // Skip common stop words
    static const std::set<std::string> stop = {
        "a",  "an",  "the", "for", "with",        "using", "in",      "of",
        "to", "and", "or",  "app", "application", "ui",    "terminal"};
    while (ss >> word) {
      std::string lw = word;
      std::transform(lw.begin(), lw.end(), lw.begin(), ::tolower);
      if (stop.find(lw) == stop.end()) {
        app_name = word;
        if (!app_name.empty()) {
          app_name[0] = static_cast<char>(
              ::toupper(static_cast<unsigned char>(app_name[0])));
        }
        break;
      }
    }
    if (app_name.empty()) {
      app_name = "MyApp";
    }
  }

  // Current date string
  std::time_t t = std::time(nullptr);
  char date_buf[32];
  std::strftime(date_buf, sizeof(date_buf), "%Y-%m-%d", std::localtime(&t));

  return {
      {"APP_NAME", app_name},
      {"TIMESTAMP", std::string(date_buf)},
      {"DESCRIPTION", req.description},
  };
}

CodeGenResult CodeGenerator::GenerateFromTemplate(const CodeGenRequest& req) {
  auto t0 = std::chrono::steady_clock::now();
  CodeGenResult result;
  result.model_used = "template";

  const CodeTemplate* tmpl = TemplateLibrary::FindBest(req.description);
  if (!tmpl) {
    // Default to dashboard when nothing matches
    const auto& templates = TemplateLibrary::BuiltinTemplates();
    if (!templates.empty()) {
      tmpl = &templates[0];
    }
  }

  if (!tmpl) {
    result.error = "No templates available";
    return result;
  }

  auto vars = DefaultVars(req);
  result.code = TemplateLibrary::Fill(*tmpl, vars);
  result.cmake_snippet = TemplateLibrary::Fill(
      CodeTemplate{"", "", {}, tmpl->cmake_snippet, ""}, vars);
  result.description = "Generated from template: " + tmpl->name;
  result.success = true;

  auto t1 = std::chrono::steady_clock::now();
  result.elapsed =
      std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0);
  return result;
}

CodeGenResult CodeGenerator::Generate(const CodeGenRequest& req) {
  if (!LLMAvailable()) {
    return GenerateFromTemplate(req);
  }

  auto t0 = std::chrono::steady_clock::now();
  CodeGenResult result;
  result.model_used = model_;

  std::string raw = QueryOllama(BuildSystemPrompt(), BuildUserPrompt(req));

  if (raw.empty()) {
    // LLM call failed — fall back
    result = GenerateFromTemplate(req);
    result.description =
        "(LLM unavailable — used template) " + result.description;
    return result;
  }

  ExtractCode(raw, result);

  if (result.code.empty()) {
    result = GenerateFromTemplate(req);
    result.description =
        "(LLM response unparseable — used template) " + result.description;
    return result;
  }

  if (result.cmake_snippet.empty() && req.include_cmake) {
    auto vars = DefaultVars(req);
    result.cmake_snippet = TemplateLibrary::Fill(
        CodeTemplate{"", "", {}, DEFAULT_CMAKE, ""}, vars);
  }

  result.description = req.description;
  result.success = true;

  auto t1 = std::chrono::steady_clock::now();
  result.elapsed =
      std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0);
  return result;
}

void CodeGenerator::GenerateAsync(
    const CodeGenRequest& req,
    std::function<void(const std::string& token)> on_token,
    std::function<void(CodeGenResult)> on_complete) {
  std::thread([req, on_token, on_complete, this]() mutable {
    // For simplicity, run synchronously in thread and fire tokens in chunks
    CodeGenResult r = Generate(req);
    if (on_token) {
      // Simulate streaming by breaking code into chunks of ~40 chars
      const std::size_t chunk_size = 40;
      for (std::size_t i = 0; i < r.code.size(); i += chunk_size) {
        on_token(r.code.substr(i, chunk_size));
      }
    }
    if (on_complete) {
      on_complete(std::move(r));
    }
  }).detach();
}

// ═════════════════════════════════════════════════════════════════════════════
// SyntaxHighlighter
// ═════════════════════════════════════════════════════════════════════════════

static const std::set<std::string>& CppKeywords() {
  static const std::set<std::string> kws = {
      "auto",
      "int",
      "void",
      "class",
      "struct",
      "if",
      "else",
      "for",
      "while",
      "do",
      "return",
      "namespace",
      "using",
      "include",
      "define",
      "template",
      "typename",
      "const",
      "static",
      "bool",
      "char",
      "float",
      "double",
      "nullptr",
      "true",
      "false",
      "new",
      "delete",
      "public",
      "private",
      "protected",
      "override",
      "virtual",
      "inline",
      "extern",
      "switch",
      "case",
      "break",
      "continue",
      "default",
      "enum",
      "union",
      "typedef",
      "long",
      "short",
      "unsigned",
      "signed",
      "sizeof",
      "operator",
      "try",
      "catch",
      "throw",
      "const_cast",
      "static_cast",
      "reinterpret_cast",
      "dynamic_cast",
  };
  return kws;
}

std::vector<SyntaxHighlighter::Token> SyntaxHighlighter::Tokenize(
    const std::string& line) {
  std::vector<Token> tokens;
  if (line.empty()) {
    return tokens;
  }

  // Preprocessor line: the whole line is one token
  if (!line.empty() && line.front() == '#') {
    tokens.push_back({line, TokenType::Preprocessor});
    return tokens;
  }

  std::size_t i = 0;
  const std::size_t n = line.size();

  while (i < n) {
    // Line comment
    if (i + 1 < n && line[i] == '/' && line[i + 1] == '/') {
      tokens.push_back({line.substr(i), TokenType::Comment});
      break;
    }

    // Block comment start
    if (i + 1 < n && line[i] == '/' && line[i + 1] == '*') {
      std::size_t end = line.find("*/", i + 2);
      std::size_t len = (end == std::string::npos) ? n - i : end - i + 2;
      tokens.push_back({line.substr(i, len), TokenType::Comment});
      i += len;
      continue;
    }

    // String literal "..."
    if (line[i] == '"') {
      std::size_t j = i + 1;
      while (j < n) {
        if (line[j] == '\\') {
          j += 2;
          continue;
        }
        if (line[j] == '"') {
          ++j;
          break;
        }
        ++j;
      }
      tokens.push_back({line.substr(i, j - i), TokenType::String});
      i = j;
      continue;
    }

    // Char literal '.'
    if (line[i] == '\'') {
      std::size_t j = i + 1;
      while (j < n) {
        if (line[j] == '\\') {
          j += 2;
          continue;
        }
        if (line[j] == '\'') {
          ++j;
          break;
        }
        ++j;
      }
      tokens.push_back({line.substr(i, j - i), TokenType::String});
      i = j;
      continue;
    }

    // Number
    if (std::isdigit(static_cast<unsigned char>(line[i])) ||
        (line[i] == '-' && i + 1 < n &&
         std::isdigit(static_cast<unsigned char>(line[i + 1])))) {
      std::size_t j = i;
      if (line[j] == '-') {
        ++j;
      }
      while (j < n && (std::isalnum(static_cast<unsigned char>(line[j])) ||
                       line[j] == '.' || line[j] == '_')) {
        ++j;
      }
      tokens.push_back({line.substr(i, j - i), TokenType::Number});
      i = j;
      continue;
    }

    // Identifier or keyword
    if (std::isalpha(static_cast<unsigned char>(line[i])) || line[i] == '_') {
      std::size_t j = i;
      while (j < n && (std::isalnum(static_cast<unsigned char>(line[j])) ||
                       line[j] == '_')) {
        ++j;
      }
      std::string word = line.substr(i, j - i);
      TokenType type = (CppKeywords().count(word) > 0) ? TokenType::Keyword
                                                       : TokenType::Normal;
      tokens.push_back({word, type});
      i = j;
      continue;
    }

    // Operators / punctuation: single char
    char c = line[i];
    bool is_op =
        (c == '+' || c == '-' || c == '*' || c == '/' || c == '=' || c == '<' ||
         c == '>' || c == '!' || c == '&' || c == '|' || c == '^' || c == '~' ||
         c == '%' || c == '?' || c == ':' || c == ';' || c == ',' || c == '.' ||
         c == '(' || c == ')' || c == '[' || c == ']' || c == '{' || c == '}');
    tokens.push_back(
        {std::string(1, c), is_op ? TokenType::Operator : TokenType::Normal});
    ++i;
  }

  return tokens;
}

ftxui::Element SyntaxHighlighter::HighlightLine(
    const std::string& line,
    const std::string& /*language*/) {
  auto tokens = Tokenize(line);
  if (tokens.empty()) {
    return text("");
  }

  Elements parts;
  parts.reserve(tokens.size());
  for (const auto& tok : tokens) {
    Element e = text(tok.text);
    switch (tok.type) {
      case TokenType::Keyword:
        e = e | bold | color(Color::Blue);
        break;
      case TokenType::String:
        e = e | color(Color::Green);
        break;
      case TokenType::Comment:
        e = e | dim | color(Color::GrayDark);
        break;
      case TokenType::Number:
        e = e | color(Color::Yellow);
        break;
      case TokenType::Preprocessor:
        e = e | color(Color::Magenta);
        break;
      case TokenType::Operator:
        e = e | color(Color::GrayLight);
        break;
      case TokenType::Normal:
      default:
        break;
    }
    parts.push_back(std::move(e));
  }
  return hbox(std::move(parts));
}

std::vector<ftxui::Element> SyntaxHighlighter::Highlight(
    const std::string& code,
    const std::string& language) {
  std::vector<Element> lines;
  std::istringstream ss(code);
  std::string line;
  while (std::getline(ss, line)) {
    lines.push_back(HighlightLine(line, language));
  }
  // If the code ends with a newline, add a trailing empty line
  if (!code.empty() && code.back() == '\n') {
    lines.push_back(HighlightLine("", language));
  }
  return lines;
}

// ═════════════════════════════════════════════════════════════════════════════
// CodePreview component
// ═════════════════════════════════════════════════════════════════════════════

ftxui::Component CodePreview(const std::string& code,
                             const std::string& language) {
  struct State {
    std::string code;
    std::string language;
    int scroll = 0;
    std::vector<Element> highlighted;

    void Rebuild() {
      highlighted = SyntaxHighlighter::Highlight(code, language);
    }
  };

  auto state = std::make_shared<State>();
  state->code = code;
  state->language = language;
  state->Rebuild();

  auto line_count = static_cast<int>(state->highlighted.size());

  class Impl : public ComponentBase {
   public:
    explicit Impl(std::shared_ptr<State> s) : state_(std::move(s)) {}

    Element OnRender() override {
      const int line_count = static_cast<int>(state_->highlighted.size());
      const int visible = 30;  // approx visible lines

      Elements lines;
      int start = std::max(0, std::min(state_->scroll, line_count - 1));
      int end = std::min(line_count, start + visible);

      for (int i = start; i < end; ++i) {
        std::string num = std::to_string(i + 1);
        while (num.size() < 4) {
          num = " " + num;
        }
        lines.push_back(hbox({
            text(num) | dim | size(WIDTH, EQUAL, 4),
            text(" │ ") | dim,
            state_->highlighted[i] | flex,
        }));
      }

      std::string header = " " + std::to_string(line_count) + " lines";

      return vbox({
                 hbox({
                     text(header) | bold,
                     filler(),
                 }) | color(Color::Cyan),
                 separator(),
                 vbox(std::move(lines)) | flex,
             }) |
             border;
    }

    bool OnEvent(Event event) override {
      int line_count = static_cast<int>(state_->highlighted.size());
      if (event == Event::ArrowUp || event == Event::Character('k')) {
        state_->scroll = std::max(0, state_->scroll - 1);
        return true;
      }
      if (event == Event::ArrowDown || event == Event::Character('j')) {
        state_->scroll = std::min(line_count - 1, state_->scroll + 1);
        return true;
      }
      if (event == Event::PageUp) {
        state_->scroll = std::max(0, state_->scroll - 20);
        return true;
      }
      if (event == Event::PageDown) {
        state_->scroll = std::min(line_count - 1, state_->scroll + 20);
        return true;
      }
      return false;
    }

   private:
    std::shared_ptr<State> state_;
  };

  (void)line_count;  // suppress unused warning when used in lambda captures
  return Make<Impl>(state);
}

// ═════════════════════════════════════════════════════════════════════════════
// CodeGenStudio component
// ═════════════════════════════════════════════════════════════════════════════

ftxui::Component CodeGenStudio(
    std::function<void(const CodeGenResult&)> on_generated) {
  struct StudioState {
    std::string description;
    int style_index = 0;
    bool feat_charts = true;
    bool feat_tables = true;
    bool feat_realtime = false;
    bool feat_map = false;
    std::string model = "llama3";
    CodeGenResult result;
    bool generating = false;
    std::string status_msg;
    std::shared_ptr<Component> preview;
  };

  auto state = std::make_shared<StudioState>();

  // Description input
  auto desc_input = Input(&state->description, "kubernetes pod monitor");

  // Style dropdown
  std::vector<std::string> styles = {"modern", "minimal", "matrix", "lcars"};
  auto style_sel = Dropdown(&styles, &state->style_index);

  // Feature checkboxes
  auto feat_charts = Checkbox("Charts", &state->feat_charts);
  auto feat_tables = Checkbox("Tables", &state->feat_tables);
  auto feat_realtime = Checkbox("Real-time", &state->feat_realtime);
  auto feat_map = Checkbox("Map", &state->feat_map);

  // Generate button
  auto gen_btn = Button("Generate →", [state, on_generated]() {
    if (state->description.empty()) {
      return;
    }
    state->generating = true;
    state->status_msg = "Generating…";

    CodeGenRequest req;
    req.description = state->description;
    req.style = std::vector<std::string>{
        "modern", "minimal", "matrix",
        "lcars"}[static_cast<std::size_t>(state->style_index)];
    if (state->feat_charts) {
      req.features.push_back("charts");
    }
    if (state->feat_tables) {
      req.features.push_back("tables");
    }
    if (state->feat_realtime) {
      req.features.push_back("real-time");
    }
    if (state->feat_map) {
      req.features.push_back("map");
    }
    req.model = state->model;

    // Run in background thread
    std::thread([state, req, on_generated]() mutable {
      CodeGenerator gen(req.model);
      auto r = gen.Generate(req);
      state->result = r;
      state->generating = false;
      state->status_msg = r.success ? ("✓ " + r.description) : ("✗ " + r.error);
      if (on_generated && r.success) {
        on_generated(r);
      }
    }).detach();
  });

  // Template button
  auto tmpl_btn = Button("From Template", [state, on_generated]() {
    if (state->description.empty()) {
      return;
    }

    CodeGenRequest req;
    req.description = state->description;
    req.model = state->model;

    CodeGenerator gen(req.model);
    state->result = gen.GenerateFromTemplate(req);
    state->status_msg = state->result.success
                            ? ("✓ " + state->result.description)
                            : ("✗ " + state->result.error);
    if (on_generated && state->result.success) {
      on_generated(state->result);
    }
  });

  // Save button
  auto save_btn = Button("Save As…", [state]() {
    if (!state->result.success || state->result.code.empty()) {
      return;
    }
    std::string path = state->description;
    // Remove spaces, add .cpp
    std::transform(path.begin(), path.end(), path.begin(),
                   [](char c) { return c == ' ' ? '_' : c; });
    path += ".cpp";
    if (state->result.WriteToFile(path)) {
      state->status_msg = "✓ Saved to " + path;
    } else {
      state->status_msg = "✗ Failed to write " + path;
    }
  });

  auto container = Container::Horizontal({
      desc_input,
      style_sel,
      feat_charts,
      feat_tables,
      feat_realtime,
      feat_map,
      gen_btn,
      tmpl_btn,
      save_btn,
  });

  return Renderer(
      container,
      [state, container, desc_input, style_sel, feat_charts, feat_tables,
       feat_realtime, feat_map, gen_btn, tmpl_btn, save_btn]() -> Element {
        // Build preview of code
        Element preview_el = text("(no code generated yet)") | dim | hcenter;
        if (!state->result.code.empty()) {
          auto lines = SyntaxHighlighter::Highlight(state->result.code);
          int total = static_cast<int>(lines.size());
          // Show up to 20 lines
          Elements visible;
          visible.reserve(std::min(total, 20));
          for (int i = 0; i < std::min(total, 20); ++i) {
            std::string num = std::to_string(i + 1);
            while (num.size() < 3) {
              num = " " + num;
            }
            visible.push_back(hbox({
                text(num) | dim | size(WIDTH, EQUAL, 3),
                text(" │ ") | dim,
                lines[i] | flex,
            }));
          }
          if (total > 20) {
            visible.push_back(
                text("  … " + std::to_string(total - 20) + " more lines …") |
                dim);
          }

          std::string hdr =
              " Generated Code (" + std::to_string(total) + " lines)";
          preview_el = vbox({
              hbox({
                  text(hdr) | bold | color(Color::Cyan),
                  filler(),
                  save_btn->Render(),
              }),
              separator(),
              vbox(std::move(visible)),
          });
        }

        // Status bar
        Color status_color = (state->status_msg.rfind("✓", 0) == 0 ||
                              state->status_msg.rfind("\xe2\x9c\x93", 0) == 0)
                                 ? Color::Green
                                 : Color::Yellow;
        if (state->generating) {
          status_color = Color::Yellow;
        }

        return vbox({
                   // Title
                   text(" 🤖 BadWolf Code Generator") | bold |
                       color(Color::Cyan) | hcenter,
                   separator(),
                   // Controls row 1
                   hbox({
                       text("Describe your app: ") | bold,
                       desc_input->Render() | flex,
                   }) | border,
                   // Controls row 2
                   hbox({
                       text("Style: "),
                       style_sel->Render() | size(WIDTH, EQUAL, 12),
                       text("  Features: "),
                       feat_charts->Render(),
                       text(" "),
                       feat_tables->Render(),
                       text(" "),
                       feat_realtime->Render(),
                       text(" "),
                       feat_map->Render(),
                       filler(),
                       gen_btn->Render(),
                       text(" "),
                       tmpl_btn->Render(),
                   }),
                   separator(),
                   // Status
                   hbox({
                       text(state->generating ? "⏳ Generating…"
                                              : state->status_msg) |
                           color(status_color),
                       filler(),
                   }),
                   separator(),
                   // Code preview
                   preview_el | flex,
               }) |
               border;
      });
}

}  // namespace ftxui::ui
