#!/usr/bin/env python3
"""
embed_geojson.py — Convert a GeoJSON file into an embeddable C++ source file.

Usage:
    python3 tools/embed_geojson.py examples/ui/world_ne110m.geojson \
        --header include/ftxui/ui/world_map_data.hpp \
        --source  src/ftxui/ui/world_map_data.cpp \
        --function WorldMapGeoJSON \
        --namespace ftxui::ui

The output C++ source splits the JSON into 30 KB chunks to stay within MSVC's
string literal size limits, then concatenates them at runtime in a single call.
"""

import argparse
import json
import os
import sys


def minify(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return json.dumps(json.loads(f.read()), separators=(",", ":"))


def escape_cpp(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_header(function_name: str, namespace: str) -> str:
    ns_open  = "\n".join(f"namespace {n} {{" for n in namespace.split("::"))
    ns_close = "\n".join("}" for _ in namespace.split("::"))
    return f"""\
// Auto-generated by tools/embed_geojson.py — do not edit manually.
// Source: Natural Earth 110m coastline + borders (public domain)

#pragma once
#include <string>

{ns_open}

/// Returns the Natural Earth 110m world map as a GeoJSON FeatureCollection
/// string. Coastlines (128 polygons) + country borders (333 lines), 8123 pts.
/// Source: Natural Earth (public domain), naturalearthdata.com
std::string {function_name}();

{ns_close}  // namespace {namespace}
"""


def generate_source(data: str, function_name: str, namespace: str,
                    header_path: str, chunk_size: int = 30_000) -> str:
    chunks = [data[i:i + chunk_size] for i in range(0, len(data), chunk_size)]

    ns_open  = "\n".join(f"namespace {n} {{" for n in namespace.split("::"))
    ns_close = "\n".join("}" for _ in namespace.split("::"))

    chunk_lines = [f'    "{escape_cpp(c)}",' for c in chunks]
    chunks_str = "\n".join(chunk_lines)

    return f"""\
// Auto-generated by tools/embed_geojson.py — do not edit manually.
// Source: Natural Earth 110m coastline + borders (public domain)

#include "{header_path}"

{ns_open}

// Split into {chunk_size // 1000} KB chunks for MSVC string literal compatibility.
static const char* const kChunks[] = {{
{chunks_str}
    nullptr
}};

std::string {function_name}() {{
    std::string result;
    result.reserve({len(data)});
    for (int i = 0; kChunks[i]; ++i) result += kChunks[i];
    return result;
}}

{ns_close}  // namespace {namespace}
"""


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input",        help="Input GeoJSON file")
    p.add_argument("--header",     default="world_map_data.hpp")
    p.add_argument("--source",     default="world_map_data.cpp")
    p.add_argument("--function",   default="WorldMapGeoJSON")
    p.add_argument("--namespace",  default="ftxui::ui")
    p.add_argument("--chunk-size", type=int, default=30_000)
    args = p.parse_args()

    print(f"Reading {args.input}...", file=sys.stderr)
    data = minify(args.input)
    print(f"Minified: {len(data):,} bytes → {len(data) // args.chunk_size + 1} chunks",
          file=sys.stderr)

    # Derive relative header include path from source file location
    src_dir   = os.path.dirname(os.path.abspath(args.source))
    hdr_abs   = os.path.abspath(args.header)
    try:
        hdr_rel = os.path.relpath(hdr_abs, src_dir)
    except ValueError:
        hdr_rel = args.header  # different drive on Windows

    header_txt = generate_header(args.function, args.namespace)
    source_txt = generate_source(data, args.function, args.namespace,
                                  hdr_rel, args.chunk_size)

    os.makedirs(os.path.dirname(os.path.abspath(args.header)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(args.source)),  exist_ok=True)

    with open(args.header, "w", encoding="utf-8") as f:
        f.write(header_txt)
    print(f"Written header: {args.header}", file=sys.stderr)

    with open(args.source, "w", encoding="utf-8") as f:
        f.write(source_txt)
    print(f"Written source: {args.source}", file=sys.stderr)


if __name__ == "__main__":
    main()
